services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=scholar_admin
      - POSTGRES_PASSWORD=scholar_pass
      - POSTGRES_DB=scholar_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
